// Generated by scripts/sync-rules.py from mimvo/rules.py. Do not edit by hand.
// mimvo 0.1.0 · report schema 2.0

import type { RuleMeta } from "./types";

export const MIMVO_VERSION = "0.1.0";
export const SCHEMA_VERSION = "2.0";

export const RULES = {
  "secret_detected": {
    "id": "secret_detected",
    "title": "Leaked secret",
    "check": "secrets",
    "severity": "critical",
    "action": "delete",
    "summary": "The record contains a credential: an API key, token, password, private key, or connection string.",
    "message": "Secret-like content detected. Delete the record and rotate the credential.",
    "remediation": [
      "Rotate or revoke the credential first. Deleting the record does not undo exposure.",
      "Delete the record from the store, and from any export or backup of it.",
      "Stop the write path from storing secrets, for example with a WriteGuard."
    ],
    "owaspId": "LLM02",
    "owasp": "LLM02: Sensitive Information Disclosure",
    "owaspUrl": "https://genai.owasp.org/llm-top-10/",
    "cwe": [
      "CWE-312"
    ]
  },
  "pii_detected": {
    "id": "pii_detected",
    "title": "Personal data",
    "check": "secrets",
    "severity": "medium",
    "action": "review",
    "summary": "The record contains personal data such as a name, email, or phone number.",
    "message": "Personal data detected; redact it or apply a retention rule. Do not treat this as a credential to rotate.",
    "remediation": [
      "Check whether the agent needs this data to do its job.",
      "Redact it, or apply your retention rule for personal data.",
      "Do not treat it as a credential to rotate."
    ],
    "owaspId": "LLM02",
    "owasp": "LLM02: Sensitive Information Disclosure",
    "owaspUrl": "https://genai.owasp.org/llm-top-10/",
    "cwe": [
      "CWE-359"
    ]
  },
  "persistent_instruction": {
    "id": "persistent_instruction",
    "title": "Hidden instruction",
    "check": "injection",
    "severity": "high",
    "action": "review",
    "summary": "The record tries to override the agent's instructions, switch its persona, or hide something from the user. It will reach the prompt as trusted context.",
    "message": "Content contains agent-directed instruction/injection phrases.",
    "remediation": [
      "Read the record. Memory should hold facts and preferences, not orders to the agent.",
      "Delete it if it is an injection; it re-enters the prompt every time it is retrieved.",
      "Trace where it came from (a scraped page, a ticket, a tool result) and filter there."
    ],
    "owaspId": "LLM01",
    "owasp": "LLM01: Prompt Injection",
    "owaspUrl": "https://genai.owasp.org/llm-top-10/",
    "cwe": [
      "CWE-1427"
    ]
  },
  "known_answer": {
    "id": "known_answer",
    "title": "Canary instruction dropped",
    "check": "injection",
    "severity": "medium",
    "action": "review",
    "summary": "Placed next to a canary instruction, the record made a language model ignore it.",
    "message": "The record stops a language model from following a canary instruction placed next to it (known-answer detection).",
    "remediation": [
      "Review the record for embedded instructions.",
      "Delete or quarantine it if it hijacks the model."
    ],
    "owaspId": "LLM01",
    "owasp": "LLM01: Prompt Injection",
    "owaspUrl": "https://genai.owasp.org/llm-top-10/",
    "cwe": [
      "CWE-1427"
    ]
  },
  "embedding_injection": {
    "id": "embedding_injection",
    "title": "Injection embedding",
    "check": "injection",
    "severity": "medium",
    "action": "review",
    "summary": "A classifier on the stored vector labels the record as prompt injection.",
    "message": "The stored embedding is classified as prompt injection by an embedding-space linear model.",
    "remediation": [
      "Review the record text for embedded instructions.",
      "Calibrate the classifier threshold on your own data if hits look benign."
    ],
    "owaspId": "LLM01",
    "owasp": "LLM01: Prompt Injection",
    "owaspUrl": "https://genai.owasp.org/llm-top-10/",
    "cwe": [
      "CWE-1427"
    ]
  },
  "memory_poisoning": {
    "id": "memory_poisoning",
    "title": "Poisoned fact",
    "check": "poisoning",
    "severity": "high",
    "action": "quarantine",
    "summary": "The record claims a security control is off: authentication, MFA, approval, or review. An agent that retrieves it may act on it.",
    "message": "Content matches a control-bypass phrase; a regex hit is a signal, not proof of a planted fact. Review before treating it as poison.",
    "remediation": [
      "Quarantine the record so retrieval stops returning it.",
      "Confirm with the control's owner whether the claim is true.",
      "Delete it if false, and find the source that wrote it."
    ],
    "owaspId": "ASI06",
    "owasp": "ASI06: Memory & Context Poisoning",
    "owaspUrl": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications/",
    "cwe": [
      "CWE-345"
    ]
  },
  "destination_redirect": {
    "id": "destination_redirect",
    "title": "Destination redirect",
    "check": "poisoning",
    "severity": "high",
    "action": "review",
    "summary": "The record routes payments or data to a new destination.",
    "message": "Content redirects payments or data to a new destination; confirm the change before it is remembered.",
    "remediation": [
      "Confirm the change through a channel other than the agent's memory.",
      "Delete the record if nobody authorised the new destination."
    ],
    "owaspId": "ASI06",
    "owasp": "ASI06: Memory & Context Poisoning",
    "owaspUrl": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications/",
    "cwe": [
      "CWE-345"
    ]
  },
  "poisoning_cluster": {
    "id": "poisoning_cluster",
    "title": "Poisoning cluster",
    "check": "poisoning",
    "severity": "low",
    "action": "review",
    "summary": "The record is one of several near-identical records, the pattern of multi-document poisoning.",
    "message": "Content is one of several near-identical retrieved records, the multi-document poisoning pattern; confirm they are legitimate copies.",
    "remediation": [
      "Compare the records in the cluster; legitimate copies of a template also match.",
      "Remove the copies if they were planted to outvote the truth."
    ],
    "owaspId": "ASI06",
    "owasp": "ASI06: Memory & Context Poisoning",
    "owaspUrl": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications/",
    "cwe": [
      "CWE-345"
    ]
  },
  "hub_record": {
    "id": "hub_record",
    "title": "Retrieval hub",
    "check": "poisoning",
    "severity": "low",
    "action": "review",
    "summary": "The record is a nearest neighbour of unusually many others, so it is retrieved for many unrelated queries.",
    "message": "This record appears in unusually many other records' nearest neighbours, the hubness pattern of a passage written to be retrieved for many queries.",
    "remediation": [
      "Read the record; text written to match every query is a poisoning signal.",
      "Delete it if its content has no reason to be that central."
    ],
    "owaspId": "ASI06",
    "owasp": "ASI06: Memory & Context Poisoning",
    "owaspUrl": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications/",
    "cwe": [
      "CWE-345"
    ]
  },
  "adversarial_text": {
    "id": "adversarial_text",
    "title": "Adversarial text",
    "check": "poisoning",
    "severity": "medium",
    "action": "review",
    "summary": "Part of the record reads as machine-optimised rather than natural text.",
    "message": "A span of this content reads as machine-optimised rather than natural text (chunk-wise language-model perplexity).",
    "remediation": [
      "Look for gibberish suffixes or token soup in the record.",
      "Delete it if the span was optimised to steer retrieval or generation."
    ],
    "owaspId": "ASI06",
    "owasp": "ASI06: Memory & Context Poisoning",
    "owaspUrl": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications/",
    "cwe": [
      "CWE-1039"
    ]
  },
  "embedding_mismatch": {
    "id": "embedding_mismatch",
    "title": "Tampered vector",
    "check": "poisoning",
    "severity": "medium",
    "action": "quarantine",
    "summary": "The stored vector does not match a fresh embedding of the record text.",
    "message": "The stored vector does not match a fresh embedding of the text; the vector may have been written directly or tampered with.",
    "remediation": [
      "Quarantine the record; its vector may have been written directly.",
      "Re-embed it with the store's model, or delete it.",
      "Check who has write access to the vector column."
    ],
    "owaspId": "ASI06",
    "owasp": "ASI06: Memory & Context Poisoning",
    "owaspUrl": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications/",
    "cwe": [
      "CWE-345"
    ]
  },
  "temporal_contradiction": {
    "id": "temporal_contradiction",
    "title": "Contradicts older memory",
    "check": "poisoning",
    "severity": "medium",
    "action": "review",
    "summary": "A newer record contradicts the older records around it.",
    "message": "A newer record contradicts older established neighbours; confirm the update is legitimate.",
    "remediation": [
      "Read the record and confirm with its owner whether the statement is true.",
      "If it is not, quarantine or delete it so the agent stops retrieving it.",
      "Find the write path that stored it and add a write-time check there."
    ],
    "owaspId": "ASI06",
    "owasp": "ASI06: Memory & Context Poisoning",
    "owaspUrl": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications/",
    "cwe": [
      "CWE-345"
    ]
  },
  "retrieval_flip": {
    "id": "retrieval_flip",
    "title": "Answer flip",
    "check": "poisoning",
    "severity": "medium",
    "action": "review",
    "summary": "Removing the record changes the answers to questions about its topic.",
    "message": "Removing this record changes the answer to probe questions generated from it; it may be the sole source of a planted fact.",
    "remediation": [
      "Read the record and confirm with its owner whether the statement is true.",
      "If it is not, quarantine or delete it so the agent stops retrieving it.",
      "Find the write path that stored it and add a write-time check there."
    ],
    "owaspId": "ASI06",
    "owasp": "ASI06: Memory & Context Poisoning",
    "owaspUrl": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications/",
    "cwe": [
      "CWE-345"
    ]
  }
} as const satisfies Record<string, RuleMeta>;

export type RuleId = keyof typeof RULES;
