"""Regenerate lib/rules.generated.ts from the mimvo package's rule catalogue.

The dashboard shows the same titles, severities, actions, OWASP items, CWE ids
and fix steps as `mimvo scan --report`. Run this after changing
`mimvo/rules.py` so the two never drift:

    git clone https://github.com/jawadhussein462/mimvo ../mimvo   # once
    npm run sync-rules   # uv run --project ../mimvo python scripts/sync-rules.py
"""

from __future__ import annotations

import json
from pathlib import Path

from mimvo import __version__
from mimvo.checks.security import InjectionCheck, PoisoningCheck, SecretsCheck
from mimvo.models.results import SCHEMA_VERSION
from mimvo.rules import RULES

OUT = Path(__file__).resolve().parent.parent / "lib" / "rules.generated.ts"

# The sentence each check writes to ScanFinding.message for a code.
messages = {
    code: spec.message
    for check in (SecretsCheck, InjectionCheck, PoisoningCheck)
    for code, spec in check.specs.items()
}

rules = {
    rule.id: {
        "id": rule.id,
        "title": rule.title,
        "check": rule.category,
        "severity": rule.severity.value,
        "action": rule.action.value,
        "summary": rule.summary,
        "message": messages.get(rule.id, rule.summary),
        "remediation": list(rule.remediation),
        "owaspId": rule.owasp_id,
        "owasp": rule.owasp,
        "owaspUrl": rule.owasp_url,
        "cwe": list(rule.cwe),
    }
    for rule in RULES.values()
}

body = json.dumps(rules, indent=2, ensure_ascii=False)
OUT.write_text(
    "// Generated by scripts/sync-rules.py from mimvo/rules.py. Do not edit by hand.\n"
    f"// mimvo {__version__} · report schema {SCHEMA_VERSION}\n\n"
    'import type { RuleMeta } from "./types";\n\n'
    f'export const MIMVO_VERSION = "{__version__}";\n'
    f'export const SCHEMA_VERSION = "{SCHEMA_VERSION}";\n\n'
    f"export const RULES = {body} as const satisfies Record<string, RuleMeta>;\n\n"
    "export type RuleId = keyof typeof RULES;\n",
    encoding="utf-8",
)
print(f"wrote {OUT} ({len(rules)} rules)")
